baseURL: https://mundobsd.com/
languageCode: es-es
title: Mundo BSD
theme: PaperMod
googleAnalytics: G-74KRV4EPTD
enableEmoji: true
params:
  env: production

  mainsections:
    - posts

  assets:
    disableHLJS: true

  ShowShareButtons: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true
  
  homeInfoParams:
    Title: Hola, esto es Mundo BSD.
    Content: Aquí hablamos y compartimos información acerca de sistemas operativos basados en BSD, en especial FreeBSD.
  socialIcons:
    - name: twitter
      url: "https://twitter.com/mundobsd"

markup:
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: monokai

menu:
  main:
    - identifier: acercade
      name: Acerca De
      url: /acercade
      weight: 10